#!/usr/bin/env node

let fs = require('fs');
let Phrase = require('harbinger-complex-palindrome-detector');

let text = fs.readFileSync('phrases.txt', 'utf-8');
let palindromes = [];

text.split('\n').forEach(line => {
    let phrase = new Phrase(line);
    if(phrase.isPalindrome()) {
        console.log("Palindrome detected: ", line);
        palindromes.push(line);
    }
});

fs.writeFileSync('palindrome.txt', palindromes.join('\n'));