#!/usr/bin/env node

// Obj: Return the paragraphs from the url given as argument stripped of any references.
let urllib = require('urllib');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

// Take url as an input from the command line
let url = process.argv[2];
if(!url) {
    console.log("Enter url again");
    process.exit(1);
}

urllib.request(url, {followRedirect: true}, function(error, data, response) {

    // Simulate a document object model
    let body = data.toString();
    let {document} = (new JSDOM(body)).window;

    // Grab all the paragraphs and references
    // If u click any reference number on wikipedia page u'll find that the class associated with it is 'reference'.

    let paragraphs = document.querySelectorAll("p");
    let references = document.querySelectorAll(".reference");

    references.forEach(reference => {
        reference.remove();
    })

    paragraphs.forEach(paragraph => {
        console.log(paragraph.textContent);
    })

});